version: '3'

services:
  mongo:
    container_name: mongo
    image: tutum/mongodb
    environment:
      MONGODB_DATABASE: car
      MONGODB_USER: quarkusTest
      MONGODB_PASS: quarkusTest
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - mongo-compose-network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: '"false"'
      ME_CONFIG_BASICAUTH_USERNAME: giovane
      ME_CONFIG_BASICAUTH_PASSWORD: giovane
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: car
      ME_CONFIG_MONGODB_AUTH_USERNAME: quarkusTest
      ME_CONFIG_MONGODB_AUTH_PASSWORD: quarkusTest
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge